spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
